name: Linter

on:
  workflow_call:

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
